### ISSUE TITLE
Wrong API URLs

### ISSUE THREAD

**Issue by miniBill** [ghostrider-05/patreon-api-spec#1]
All the URLs should be `/api/oauth2/v2` but they are `/api/oauth/v2`

**Comment by ghostrider-05** [comment]
Hey, thank you for opening this issue (and sorry for causing you trouble; it was not you who did something incredibly stupid but me).

I made the specification with most code reusing parts of the Patreon library that I know is working, unfortunately the url path was something I did not test. It is now fixed and you can view the endpoint now correctly on: https://patreon.apidocumentation.com/v2-stable/reference#tag/resources/GET/api/oauth2/v2/identity (server url might be broken, but maybe a reload / switching between versions can fix that)
